### PR TITLE
Add a flag to disable unicode escaping, refactor showFieldNames configuration

### PR DESCRIPTION
**Pull request by lihaoyi**
Supersedes https://github.com/com-lihaoyi/PPrint/pull/55

the new `escapeUnicode` flag defaults to `false`, since unicode characters are common enough nowadays we should expect editors and other UIs to render them without issue. Someone who wants the old behavior can always manually set it to `true`

`showFieldNames` was added in a kind of awkward manner to avoid breaking backwards binary compatibility. It's been long enough that I think a breakage is ok, so I'm moving it to be a default argument like the rest of our pprint configuration values

### CODE REVIEW

**Comment by lolgab** [comment]
This could be a good moment to break binary compatibility since Mill is going to get 0.10 soon.
Otherwise, you could define deprecated overrides of the changed methods and pass some default values. But probably it is not worth it.

**Comment by lefou** [comment]
@lolgab I've no idea how this is related to Mills binary compatibility.

**Comment by lihaoyi** [comment]
@lefou i think the reasoning is that if we break bincompat in some library, we should try to coordinate the breakages in the dependent libraries so they all happen at once. That way people can just upgrade once to get over the combined breakage, rather than upgrading over and over for each individual breakage. 

e.g. if we break bincompat in pprint but don't have a corresponding ammonite/mill release using the new version, then anyone trying to use new pprint with old ammonite/mill would hit linking errors. And since we need to release a new incompatible ammonite/mill anyway, might as well batch any other incompatible changes into that release

**Comment by lefou** [comment]
Thanks for making this more clear. I have currently no deep insights into PPrint and am fully loaded, so I'd rather like to not have an opinion about this topic. Sorry. Regarding Mill, I envision to encapsulate more dependencies and only share a small API with build scripts (e.g. os-lib). I think Ammonite already supports this (with `--thin`) but I'm either not smart enough or it's actually very complicated to make that work with Mill.

**Comment by lolgab** [comment]
I'd say, merge this and immediately tag 0.7.0 unless there are other breaking PRs we can merge right after.

**Review by lolgab — APPROVED** [review]

**Comment by lihaoyi** [comment]
@lolgab I'm planning on doing a release of the whole com-lihaoyi ecosystem; there are a bunch of changes e.g. https://github.com/com-lihaoyi/acyclic/pull/42 that I'd like to propagate throughout all the way down to Ammonite and possibly Mill

I won't get to it tomorrow, but hopefully some time in the next 1-2 weeks

**Pull request merged**
