### PR TITLE
deps: update all sorts of stuff

### PR DESCRIPTION
**Pull request by ckipp01**
This pr goes through and makes the various updates:
  - Bumps mill to the latest 0.10.5
  - Bumps to the latest Scala versions for 2 and latest 3.1.x version
  - Drops 0.x support for ScalaJS
  - Move Scala native to 0.4.x
  - Adds in dependabot
  - Starts to cross test on 8 and 17
  - Updates checkout and java actions

### CODE REVIEW

**Comment by ckipp01** [comment]
So there is still one thing I'm trying to figure out with this. The Mima tests pass for 2.13.6, but once I bump past that the 2.13 ScalaJS check fails with
```
Found 2 issue when checking against com.lihaoyi:pprint_sjs1_2.13:0.7.3
 * static method apply(scala.collection.Iterable)java.lang.String in class pprint.StringPrefix has a different generic signature in current version, where it is (Lscala/collection/Iterable<Ljava/lang/Object;>;)Ljava/lang/String; rather than (Lscala/collection/Iterable<*>;)Ljava/lang/String;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
   filter with: ProblemFilter.exclude[IncompatibleSignatureProblem]("pprint.StringPrefix.apply")
 * method apply(scala.collection.Iterable)java.lang.String in object pprint.StringPrefix has a different generic signature in current version, where it is (Lscala/collection/Iterable<Ljava/lang/Object;>;)Ljava/lang/String; rather than (Lscala/collection/Iterable<*>;)Ljava/lang/String;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
   filter with: ProblemFilter.exclude[IncompatibleSignatureProblem]("pprint.StringPrefix.apply")
1 targets failed
pprint.js[2.13.7,1.10.1].mimaReportBinaryIssues Failed binary compatibility check! Found 2 potential problems
```

So trying to figure this out.

**Comment by lolgab** [comment]
Thank you for this @ckipp01!
About the MiMa issue, I released a new version of mill-mima which has the same behaviour as the Sbt plugin, so if you update you should be able to remove the configuration you added:
```scala
  // By default in sbt-mima IncompatibleSignatureProblem is actually turned off
  // by default due to false positives. We hit on this with 2.13 > 2.13.6 with
  // * static method apply(scala.collection.Iterable)java.lang.String in class pprint.StringPrefix has a different generic signature in current version, where it is (Lscala/collection/Iterable<Ljava/lang/Object;>;)Ljava/lang/String; rather than (Lscala/collection/Iterable<*>;)Ljava/lang/String;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
  def mimaBinaryIssueFilters = if (crossScalaVersion.startsWith("2.13"))  {
    super.mimaBinaryIssueFilters() ++ Seq(
      ProblemFilter.exclude[IncompatibleSignatureProblem]("pprint.StringPrefix.apply")
    )
  } else {
    super.mimaBinaryIssueFilters()
  }
```

**Comment by ckipp01** [comment]
> Also, I released fansi 0.4.0 with your updates.

Sounds good. I updated this and to the new `mill-mima`.

**Comment by lolgab** [comment]
Sorry, forgot to mention `sourcecode` `0.3.0` which was released with your changes.

**Review by lolgab — APPROVED** [review]

**Pull request merged**
